# Generated by Django 5.2.5 on 2025-08-20 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0003_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('reveal_date', models.DateField(help_text='Fixtures will show real team names on/after this date')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['tournament', 'round_number', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['tournament', 'team_number']},
        ),
        migrations.AlterField(
            model_name='matches',
            name='start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='Matches.tournament'),
        ),
        migrations.AddField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Matches.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('tournament', 'team_number')},
        ),
    ]
