# Generated by Django 5.2.5 on 2025-08-20 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0004_tournament_alter_matches_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='tournament',
        ),
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['round_number', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
