# Generated by Django 5.2.5 on 2025-08-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0006_galleryitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['round_number', 'match_number', 'start_time']},
        ),
        migrations.AddField(
            model_name='matches',
            name='match_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
