# Generated by Django 5.2.5 on 2025-08-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Matches', '0007_alter_matches_options_matches_match_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['round_number', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='match_number',
        ),
    ]
